//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersRolesMapping
    {
        public int UsersRolesMappingID { get; set; }
        public int UserID { get; set; }
        public int UserRoleID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedBy { get; set; }
    }
}
